attempting to add metadata for coanzse.org
clarin-eric/SPF-SPs-metadata pull request #275
Opened 2023-09-11 18:37 UTC by stcoats

2023-09-13 09:45 UTC, andmor- commented
I am a little confused by this. There are [two new files](https://github.com/clarin-eric/SPF-SPs-metadata/pull/275/files), which one is to keep? 

There should only be one file (placed in: `/metadata/coanzse.org.xml`)

2023-09-13 10:13 UTC, stcoats commented
I am also confused, and more than a little! 😄 I don't know why there are two files. I think somehow in the process of attempting to follow the bafflingly complex, multi-step, over-many-different pages-distributed instructions for setting up an SPF, I might have mistakenly put a .conf file in the wrong place or used the wrong XPath expression or recreated a cloned directory in the wrong place or attempted to merge the wrong branch with the wrong master or something. I really have no idea. 
Looking in my local CLARIN directory, which I cloned as part of the tutorial instructions, it appears that the file I created in there is 191 lines long. That means it would be the second of the two files. I guess just delete the first one? However, I also vaguely remember part of the tutorial requiring me to make various changes and then to to `rsync` different files between `etc` and the CLARIN cloned directory, or something along those lines? Sorry for not being an expert in this, and thanks for any help you can provide.

2023-09-13 11:43 UTC, andmor- commented
The files seem different. I will use the one in `metadata/coanzse.org.xml` for now.
Instead of `rsync` you can just edit the configuration files in place on your server.

2023-09-13 11:53 UTC, andmor- requested changes
Please choose(generate) one X509 certificate and replace the 3 ones in your fork by it.

2023-09-13 11:53 UTC, andmor- commented on metadata/coanzse.org.xml
> +<ds:X509Certificate>
There are currently 3 certificates in this file and only one is expected.
We advice you use the same certificate for both: signing and encryption. This certificate should be self-signed (currently it is a letsencrypt signed certificate) and have a validity of 4-5 years.

2023-09-13 11:53 UTC, andmor- commented on metadata/coanzse.org.xml
> +            <mdui:PrivacyStatementURL xml:lang="en">https://catalog.clarin.eu/privacy_statement.xhtml</mdui:PrivacyStatementURL>
For testing this will do, but you will need your own Privacy Statement running on you own URLs

2023-09-15 11:48 UTC, stcoats commented
Hi again, I updated the coanzse.org.xml file with the new certificate and attempted a push!

2023-09-18 12:32 UTC, andmor- commented
Closing in favor of #277

2023-09-18 12:32 UTC, closed without merging